#
# This file is part of the pinterest-ruby gem. Copyright (C) 2017 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at https://choosealicense.com/licenses/mit.
#

AllCops:
  TargetRubyVersion: 2.2
  Include:
    - "Rakefile"
    - "Gemfile"
  Exclude:
    - "spec/**/*"

Alias:
  Enabled: false

AsciiComments:
  Enabled: false

Blocks:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

CyclomaticComplexity:
  Max: 15

Documentation:
  Enabled: false

EachWithObject:
  Enabled: false

IndentHash:
  Enabled: false

IndentationConsistency:
  Enabled: false

LineLength:
  Max: 160

ParameterLists:
  Max: 6

RegexpLiteral:
  Enabled: false

SignalException:
  Enabled: false

SpaceInsideHashLiteralBraces:
  Enabled: false

StringLiterals:
  Enabled: false

StringLiteralsInInterpolation:
  Enabled: false

WordArray:
  Enabled: false